# Generated by Django 6.0 on 2026-07-29 11:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(db_index=True, editable=False, max_length=20, unique=True)),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('gst_number', models.CharField(blank=True, max_length=20)),
                ('alternate_phone', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number.', regex='^\\+?[0-9]{10,15}$')])),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='customers/')),
                ('address_line_1', models.CharField(max_length=255)),
                ('address_line_2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('state', models.CharField(db_index=True, max_length=100)),
                ('country', models.CharField(default='India', max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('total_shipments', models.PositiveIntegerField(default=0)),
                ('completed_shipments', models.PositiveIntegerField(default=0)),
                ('cancelled_shipments', models.PositiveIntegerField(default=0)),
                ('is_verified', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'ordering': ['user__first_name', 'user__last_name'],
                'indexes': [models.Index(fields=['customer_id'], name='customers_c_custome_ec5e63_idx'), models.Index(fields=['city'], name='customers_c_city_571324_idx'), models.Index(fields=['state'], name='customers_c_state_04810f_idx'), models.Index(fields=['created_at'], name='customers_c_created_1ed0f4_idx'), models.Index(fields=['is_verified'], name='customers_c_is_veri_2aa730_idx')],
            },
        ),
    ]
