# Generated by Django 6.0 on 2026-07-29 11:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('category', models.CharField(choices=[('GENERAL', 'General Inquiry'), ('SHIPMENT', 'Shipment Issue'), ('DELIVERY', 'Delivery Issue'), ('PAYMENT', 'Payment'), ('COMPLAINT', 'Complaint'), ('FEEDBACK', 'Feedback'), ('OTHER', 'Other')], db_index=True, default='GENERAL', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], db_index=True, default='PENDING', max_length=20)),
                ('admin_reply', models.TextField(blank=True)),
                ('replied_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('replied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replied_contacts', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contact Request',
                'verbose_name_plural': 'Contact Requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='contact_con_status_9a9384_idx'), models.Index(fields=['category'], name='contact_con_categor_db7973_idx'), models.Index(fields=['created_at'], name='contact_con_created_eb2247_idx'), models.Index(fields=['user', 'status'], name='contact_con_user_id_1e4515_idx')],
            },
        ),
    ]
