# Generated by Django 6.0 on 2026-07-29 11:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
        ('shipments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_code', models.CharField(db_index=True, editable=False, max_length=20, unique=True)),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('origin', models.CharField(db_index=True, max_length=200)),
                ('destination', models.CharField(db_index=True, max_length=200)),
                ('total_distance', models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('estimated_duration', models.PositiveIntegerField(default=0, help_text='Duration in minutes')),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('ASSIGNED', 'Assigned'), ('STARTED', 'Started'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PLANNED', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routes', to='drivers.driver')),
            ],
            options={
                'verbose_name': 'Route',
                'verbose_name_plural': 'Routes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RouteShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_number', models.PositiveIntegerField()),
                ('delivered', models.BooleanField(db_index=True, default=False)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_shipments', to='routes.route')),
                ('shipment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='route_assignment', to='shipments.shipment')),
            ],
            options={
                'verbose_name': 'Route Shipment',
                'verbose_name_plural': 'Route Shipments',
                'ordering': ['stop_number'],
            },
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['route_code'], name='routes_rout_route_c_aedda7_idx'),
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['driver'], name='routes_rout_driver__1fc8f6_idx'),
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['status'], name='routes_rout_status_fbf2dd_idx'),
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['origin'], name='routes_rout_origin_dbefd1_idx'),
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['destination'], name='routes_rout_destina_c53fb8_idx'),
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['created_at'], name='routes_rout_created_31febf_idx'),
        ),
        migrations.AddIndex(
            model_name='routeshipment',
            index=models.Index(fields=['route'], name='routes_rout_route_i_5861c4_idx'),
        ),
        migrations.AddIndex(
            model_name='routeshipment',
            index=models.Index(fields=['shipment'], name='routes_rout_shipmen_bf72e9_idx'),
        ),
        migrations.AddIndex(
            model_name='routeshipment',
            index=models.Index(fields=['stop_number'], name='routes_rout_stop_nu_a0ee51_idx'),
        ),
        migrations.AddIndex(
            model_name='routeshipment',
            index=models.Index(fields=['delivered'], name='routes_rout_deliver_53f7aa_idx'),
        ),
        migrations.AddConstraint(
            model_name='routeshipment',
            constraint=models.UniqueConstraint(fields=('route', 'stop_number'), name='unique_route_stop'),
        ),
    ]
