# Generated by Django 6.0 on 2026-07-29 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_code', models.CharField(editable=False, max_length=20, unique=True)),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(default='India', max_length=100)),
                ('postal_code', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Destination',
                'verbose_name_plural': 'Destinations',
                'ordering': ['city', 'name'],
                'indexes': [models.Index(fields=['city'], name='destination_city_ec88bc_idx'), models.Index(fields=['state'], name='destination_state_0b1795_idx'), models.Index(fields=['country'], name='destination_country_2ade19_idx'), models.Index(fields=['is_active'], name='destination_is_acti_09f11c_idx')],
            },
        ),
    ]
