# Generated by Django 6.0 on 2026-07-29 11:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_id', models.CharField(db_index=True, editable=False, max_length=20, unique=True)),
                ('license_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('license_expiry', models.DateField()),
                ('vehicle_type', models.CharField(choices=[('BIKE', 'Bike'), ('VAN', 'Van'), ('MINI_TRUCK', 'Mini Truck'), ('TRUCK', 'Truck')], db_index=True, max_length=20)),
                ('vehicle_number', models.CharField(db_index=True, max_length=30, unique=True)),
                ('vehicle_model', models.CharField(max_length=100)),
                ('vehicle_capacity', models.PositiveIntegerField(help_text='Capacity in KG', validators=[django.core.validators.MinValueValidator(1)])),
                ('alternate_phone', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number.', regex='^\\+?[0-9]{10,15}$')])),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='drivers/')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('ON_DELIVERY', 'On Delivery'), ('OFF_DUTY', 'Off Duty'), ('ON_LEAVE', 'On Leave')], db_index=True, default='AVAILABLE', max_length=20)),
                ('current_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('current_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('total_deliveries', models.PositiveIntegerField(default=0)),
                ('successful_deliveries', models.PositiveIntegerField(default=0)),
                ('cancelled_deliveries', models.PositiveIntegerField(default=0)),
                ('rating', models.DecimalField(decimal_places=2, default=5.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('is_verified', models.BooleanField(default=False)),
                ('joined_date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Driver',
                'verbose_name_plural': 'Drivers',
                'ordering': ['user__first_name', 'user__last_name'],
                'indexes': [models.Index(fields=['driver_id'], name='drivers_dri_driver__6af68b_idx'), models.Index(fields=['status'], name='drivers_dri_status_d7a5f5_idx'), models.Index(fields=['vehicle_type'], name='drivers_dri_vehicle_8c7237_idx'), models.Index(fields=['license_number'], name='drivers_dri_license_ce5f7e_idx'), models.Index(fields=['vehicle_number'], name='drivers_dri_vehicle_a49268_idx'), models.Index(fields=['is_verified'], name='drivers_dri_is_veri_98c4c3_idx'), models.Index(fields=['created_at'], name='drivers_dri_created_9cae56_idx')],
            },
        ),
    ]
