# Generated by Django 6.0 on 2026-08-04 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='proof_of_delivery',
            field=models.ImageField(blank=True, null=True, upload_to='proof_of_delivery/'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='proof_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
